name: secure_messenger
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  firebase_database: ^10.2.4
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  local_auth: ^2.1.6
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  encrypt: ^5.0.1
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  path: ^1.8.3
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  image_picker: ^1.0.2
  flutter_sound_record: ^3.3.2
  permission_handler: ^10.4.3
  path_provider: ^2.1.0
  video_player: ^2.7.1
  audioplayers: ^5.1.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
